Repository danvk/source-map-explorer, pull requests merged in 2020-02, with the labels that each got.

#160 Fix coverages for inlined code exclusion
  src/coverage.ts
Labels: 🐛 bug

#165 Fix slowness
  src/app-error.ts
  src/explore.ts
  tests/api.test.ts
  tests/app-error.test.ts
  tests/cli.test.ts
  tests/data/invalid-map-column.js
  tests/data/invalid-map-line.js
  tests/generate-data/README.md
  tests/generate-data/build.js
  tests/generate-data/package-lock.json
  tests/generate-data/package.json
  tests/generate-data/src/invalid-map-column.1.js
  tests/generate-data/src/invalid-map-column.2.js
  tests/generate-data/src/invalid-map-line.1.js
  tests/generate-data/src/invalid-map-line.2.js
Labels: 🐛 bug

#162 Collapse non-contributing directories
  src/api.ts
  src/html.ts
  tests/__snapshots__/cli.test.ts.snap
  tests/__snapshots__/html.test.ts.snap
  tests/html.test.ts
Labels: 🚀 enhancement

#167 Collapse non-contributing directories
  src/html.ts
  tests/__snapshots__/cli.test.ts.snap
  tests/__snapshots__/html.test.ts.snap
  tests/html.test.ts
Labels: 🐛 bug

#169 Update Travis config and deal with EOLs
  .gitattributes
  .travis.yml
Labels: 🔧 internal
